#ifndef __PINASSIGNMENT_H__
#define __PINASSIGNMENT_H__

/* 这个文件站在SOC的视角,对所有引脚进行分配 */
/* SOC NAME + PACKAGE */
#define STM32F103xB_LQFP48  (1)
#define STM32F103xE_LQFP144  (2)  



#define SOC_NAME  STM32F103xB_LQFP48


#define PORTA   GPIOA
#define PORTB   GPIOB
#define PORTC   GPIOC
#define PORTD   GPIOD
#define PORTE   GPIOE
#define PORTF   GPIOF
#define PORTG   GPIOG
#define PORTH   GPIOH

#define PIN_0   GPIO_PIN_0
#define PIN_1   GPIO_PIN_1
#define PIN_2   GPIO_PIN_2
#define PIN_3   GPIO_PIN_3
#define PIN_4   GPIO_PIN_4
#define PIN_5   GPIO_PIN_5
#define PIN_6   GPIO_PIN_6
#define PIN_7   GPIO_PIN_7
#define PIN_8   GPIO_PIN_8
#define PIN_9   GPIO_PIN_9
#define PIN_10   GPIO_PIN_10
#define PIN_11   GPIO_PIN_11
#define PIN_12   GPIO_PIN_12
#define PIN_13   GPIO_PIN_13
#define PIN_14   GPIO_PIN_14
#define PIN_15   GPIO_PIN_15


struct pinType
{
    GPIO_TypeDef* port;
    uint16_t     pin;
};

#define CON_TYPE     const struct pinType
#define EX_CON_TYPE  extern const struct pinType



/* STM32F103xE_LQFP144 的引脚 */
#if (SOC_NAME == STM32F103xE_LQFP144)
EX_CON_TYPE PIN_INDEX_1;
EX_CON_TYPE PIN_INDEX_2;
EX_CON_TYPE PIN_INDEX_3;
EX_CON_TYPE PIN_INDEX_4;
EX_CON_TYPE PIN_INDEX_5;
EX_CON_TYPE PIN_INDEX_6;
EX_CON_TYPE PIN_INDEX_7;
EX_CON_TYPE PIN_INDEX_8;
EX_CON_TYPE PIN_INDEX_9;
EX_CON_TYPE PIN_INDEX_10;
EX_CON_TYPE PIN_INDEX_11;
EX_CON_TYPE PIN_INDEX_12;
EX_CON_TYPE PIN_INDEX_13;
EX_CON_TYPE PIN_INDEX_14;
EX_CON_TYPE PIN_INDEX_15;
EX_CON_TYPE PIN_INDEX_16;
EX_CON_TYPE PIN_INDEX_17;
EX_CON_TYPE PIN_INDEX_18;
EX_CON_TYPE PIN_INDEX_19;
EX_CON_TYPE PIN_INDEX_20;
EX_CON_TYPE PIN_INDEX_21;
EX_CON_TYPE PIN_INDEX_22;
EX_CON_TYPE PIN_INDEX_23;
EX_CON_TYPE PIN_INDEX_24;
EX_CON_TYPE PIN_INDEX_25;
EX_CON_TYPE PIN_INDEX_26;
EX_CON_TYPE PIN_INDEX_27;
EX_CON_TYPE PIN_INDEX_28;
EX_CON_TYPE PIN_INDEX_29;
EX_CON_TYPE PIN_INDEX_30;
EX_CON_TYPE PIN_INDEX_31;
EX_CON_TYPE PIN_INDEX_32;
EX_CON_TYPE PIN_INDEX_33;
EX_CON_TYPE PIN_INDEX_34;
EX_CON_TYPE PIN_INDEX_35;
EX_CON_TYPE PIN_INDEX_36;
EX_CON_TYPE PIN_INDEX_37;
EX_CON_TYPE PIN_INDEX_38;
EX_CON_TYPE PIN_INDEX_39;
EX_CON_TYPE PIN_INDEX_40;
EX_CON_TYPE PIN_INDEX_41;
EX_CON_TYPE PIN_INDEX_42;
EX_CON_TYPE PIN_INDEX_43;
EX_CON_TYPE PIN_INDEX_44;
EX_CON_TYPE PIN_INDEX_45;
EX_CON_TYPE PIN_INDEX_46;
EX_CON_TYPE PIN_INDEX_47;
EX_CON_TYPE PIN_INDEX_48;
EX_CON_TYPE PIN_INDEX_49;
EX_CON_TYPE PIN_INDEX_50;
EX_CON_TYPE PIN_INDEX_51;
EX_CON_TYPE PIN_INDEX_52;
EX_CON_TYPE PIN_INDEX_53;
EX_CON_TYPE PIN_INDEX_54;
EX_CON_TYPE PIN_INDEX_55;
EX_CON_TYPE PIN_INDEX_56;
EX_CON_TYPE PIN_INDEX_57;
EX_CON_TYPE PIN_INDEX_58;
EX_CON_TYPE PIN_INDEX_59;
EX_CON_TYPE PIN_INDEX_60;
EX_CON_TYPE PIN_INDEX_61;
EX_CON_TYPE PIN_INDEX_62;
EX_CON_TYPE PIN_INDEX_63;
EX_CON_TYPE PIN_INDEX_64;
EX_CON_TYPE PIN_INDEX_65;
EX_CON_TYPE PIN_INDEX_66;
EX_CON_TYPE PIN_INDEX_67;
EX_CON_TYPE PIN_INDEX_68;
EX_CON_TYPE PIN_INDEX_69;
EX_CON_TYPE PIN_INDEX_70;
EX_CON_TYPE PIN_INDEX_71;
EX_CON_TYPE PIN_INDEX_72;
EX_CON_TYPE PIN_INDEX_73;
EX_CON_TYPE PIN_INDEX_74;
EX_CON_TYPE PIN_INDEX_75;
EX_CON_TYPE PIN_INDEX_76;
EX_CON_TYPE PIN_INDEX_77;
EX_CON_TYPE PIN_INDEX_78;
EX_CON_TYPE PIN_INDEX_79;
EX_CON_TYPE PIN_INDEX_80;
EX_CON_TYPE PIN_INDEX_81;
EX_CON_TYPE PIN_INDEX_82;
EX_CON_TYPE PIN_INDEX_83;
EX_CON_TYPE PIN_INDEX_84;
EX_CON_TYPE PIN_INDEX_85;
EX_CON_TYPE PIN_INDEX_86;
EX_CON_TYPE PIN_INDEX_87;
EX_CON_TYPE PIN_INDEX_88;
EX_CON_TYPE PIN_INDEX_89;
EX_CON_TYPE PIN_INDEX_90;
EX_CON_TYPE PIN_INDEX_91;
EX_CON_TYPE PIN_INDEX_92;
EX_CON_TYPE PIN_INDEX_93;
EX_CON_TYPE PIN_INDEX_94;
EX_CON_TYPE PIN_INDEX_95;
EX_CON_TYPE PIN_INDEX_96;
EX_CON_TYPE PIN_INDEX_97;
EX_CON_TYPE PIN_INDEX_98;
EX_CON_TYPE PIN_INDEX_99;
EX_CON_TYPE PIN_INDEX_100;
EX_CON_TYPE PIN_INDEX_101;
EX_CON_TYPE PIN_INDEX_102;
EX_CON_TYPE PIN_INDEX_103;
EX_CON_TYPE PIN_INDEX_104;
EX_CON_TYPE PIN_INDEX_105;
EX_CON_TYPE PIN_INDEX_106;
EX_CON_TYPE PIN_INDEX_107;
EX_CON_TYPE PIN_INDEX_108;
EX_CON_TYPE PIN_INDEX_109;
EX_CON_TYPE PIN_INDEX_110;
EX_CON_TYPE PIN_INDEX_111;
EX_CON_TYPE PIN_INDEX_112;
EX_CON_TYPE PIN_INDEX_113;
EX_CON_TYPE PIN_INDEX_114;
EX_CON_TYPE PIN_INDEX_115;
EX_CON_TYPE PIN_INDEX_116;
EX_CON_TYPE PIN_INDEX_117;
EX_CON_TYPE PIN_INDEX_118;
EX_CON_TYPE PIN_INDEX_119;
EX_CON_TYPE PIN_INDEX_120;
EX_CON_TYPE PIN_INDEX_121;
EX_CON_TYPE PIN_INDEX_122;
EX_CON_TYPE PIN_INDEX_123;
EX_CON_TYPE PIN_INDEX_124;
EX_CON_TYPE PIN_INDEX_125;
EX_CON_TYPE PIN_INDEX_126;
EX_CON_TYPE PIN_INDEX_127;
EX_CON_TYPE PIN_INDEX_128;
EX_CON_TYPE PIN_INDEX_129;
EX_CON_TYPE PIN_INDEX_130;
EX_CON_TYPE PIN_INDEX_131;
EX_CON_TYPE PIN_INDEX_132;
EX_CON_TYPE PIN_INDEX_133;
EX_CON_TYPE PIN_INDEX_134;
EX_CON_TYPE PIN_INDEX_135;
EX_CON_TYPE PIN_INDEX_136;
EX_CON_TYPE PIN_INDEX_137;
EX_CON_TYPE PIN_INDEX_138;
EX_CON_TYPE PIN_INDEX_139;
EX_CON_TYPE PIN_INDEX_140;
EX_CON_TYPE PIN_INDEX_141;
EX_CON_TYPE PIN_INDEX_142;
EX_CON_TYPE PIN_INDEX_143;
EX_CON_TYPE PIN_INDEX_144;

#endif

/* STM32F407ZET6_UFBGA176_25 的引脚 */
#if (SOC_NAME == STM32F103xB_LQFP48)
EX_CON_TYPE PIN_INDEX_1;
EX_CON_TYPE PIN_INDEX_2;
EX_CON_TYPE PIN_INDEX_3;
EX_CON_TYPE PIN_INDEX_4;
EX_CON_TYPE PIN_INDEX_5;
EX_CON_TYPE PIN_INDEX_6;
EX_CON_TYPE PIN_INDEX_7;
EX_CON_TYPE PIN_INDEX_8;
EX_CON_TYPE PIN_INDEX_9;
EX_CON_TYPE PIN_INDEX_10;
EX_CON_TYPE PIN_INDEX_11;
EX_CON_TYPE PIN_INDEX_12;
EX_CON_TYPE PIN_INDEX_13;
EX_CON_TYPE PIN_INDEX_14;
EX_CON_TYPE PIN_INDEX_15;
EX_CON_TYPE PIN_INDEX_16;
EX_CON_TYPE PIN_INDEX_17;
EX_CON_TYPE PIN_INDEX_18;
EX_CON_TYPE PIN_INDEX_19;
EX_CON_TYPE PIN_INDEX_20;
EX_CON_TYPE PIN_INDEX_21;
EX_CON_TYPE PIN_INDEX_22;
EX_CON_TYPE PIN_INDEX_23;
EX_CON_TYPE PIN_INDEX_24;
EX_CON_TYPE PIN_INDEX_25;
EX_CON_TYPE PIN_INDEX_26;
EX_CON_TYPE PIN_INDEX_27;
EX_CON_TYPE PIN_INDEX_28;
EX_CON_TYPE PIN_INDEX_29;
EX_CON_TYPE PIN_INDEX_30;
EX_CON_TYPE PIN_INDEX_31;
EX_CON_TYPE PIN_INDEX_32;
EX_CON_TYPE PIN_INDEX_33;
EX_CON_TYPE PIN_INDEX_34;
EX_CON_TYPE PIN_INDEX_35;
EX_CON_TYPE PIN_INDEX_36;
EX_CON_TYPE PIN_INDEX_37;
EX_CON_TYPE PIN_INDEX_38;
EX_CON_TYPE PIN_INDEX_39;
EX_CON_TYPE PIN_INDEX_40;
EX_CON_TYPE PIN_INDEX_41;
EX_CON_TYPE PIN_INDEX_42;
EX_CON_TYPE PIN_INDEX_43;
EX_CON_TYPE PIN_INDEX_44;
EX_CON_TYPE PIN_INDEX_45;
EX_CON_TYPE PIN_INDEX_46;
EX_CON_TYPE PIN_INDEX_47;
EX_CON_TYPE PIN_INDEX_48;

#endif

#define GET_PORT(index) (index).port
#define GET_PIN(index)  (index).pin


#endif

